xarray-contrib/cf-xarray

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

Closes #3
Partially implements #4

Add getitem and actually parse attrs

---

README.md
cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

support for 'cell_measures' in DataArrays

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

Look for & prioritize "coordinates" attribute when searching.

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

Add describe.

---

ci/doc.yml
doc/api.rst
doc/conf.py
doc/index.rst

@keewis this was really easy to set up. Thanks!

Add api using sphinx_autosummary_accessors

---

.github/workflows/ci.yaml
ci/upstream-dev-env.yml

Add upstream-dev CI

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

Support variable positional args.

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

Modify docstrings of wrapped functions.

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py
doc/examples/introduction.ipynb
doc/whats-new.rst

Time accessor

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py
ci/doc.yml
ci/environment.yml

This allows plotting with variable names, not jsut cf names

Fix mapping for VAR_KEYWORD type kwargs.

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

Bugfix for missing variables in coordinate string

---

cf_xarray/accessor.py
cf_xarray/tests/datasets.py
cf_xarray/tests/test_accessor.py
doc/whats-new.rst

Closes #87 
Z : standard_names, axis
vertical : positive
cc @kthyng @jthielen

Separate vertical from Z

---

cf_xarray/accessor.py
cf_xarray/tests/datasets.py
cf_xarray/tests/test_accessor.py

Fix bug when coordinates is in both attrs and encoding

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

Update standard_name list in .describe()

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

Fix [standard_name] when variable is in coords

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

Fix cell measures parser

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py
cf_xarray/utils.py
doc/examples/introduction.ipynb

See https://github.com/xarray-contrib/cf-xarray/issues/99#issuecomment-727984869

Allow any cell measure

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py
doc/whats-new.rst

Support Dataset.cf.cell_measures

---

.github/workflows/ci.yaml
ci/doc.yml
ci/environment.yml
ci/upstream-dev-env.yml

Use `matplotlib-base` and `pytest-xdist`

CI upgrades

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py
doc/whats-new.rst

Use standard name mapper in more places.

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py
doc/whats-new.rst

Rework attribute rewriting, .cf.data_vars, .cf.coords

---

ci/doc.yml
doc/examples/introduction.ipynb

Update doc build

---

.github/workflows/ci.yaml
.github/workflows/pre-commit.yaml
cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py
doc/whats-new.rst

Closes #143 
Need to add test for:

implement names and labels

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py
doc/whats-new.rst

Support GroupBy iteration and arithmetic

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

Do not get bounds when extracting a DataArray

---

.deepsource.toml
cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py
cf_xarray/utils.py

Hi :wave: I ran the [DeepSource](https://deepsource.io) static analyzer on the forked copy of this repo and found some interesting code quality [issues](https://deepsource.io/gh/withshubh/cf-xarray/issues/). This PR fixes a few of them.
- Removed unnecessary comprehension
- Used literal syntax instead of function calls to create data structure
- Used literal syntax to create data structure
- added .deepsource.toml file

Fix: code quality issues

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

cf.data_vars skips coords

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

Added signatures to use dictionaries with `cf.rename`.

add name_dict and new_name_or_name_dict

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

- ignore bad cell_measures
- ignore bounds variable when provided a scalar key
Closes #195
Closes #191

Updates to getitem

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py
doc/api.rst
doc/whats-new.rst

Add differentiate with positive_upward flag.

---

cf_xarray/__init__.py
setup.cfg

Add __version__

---

cf_xarray/accessor.py
cf_xarray/criteria.py
cf_xarray/tests/test_accessor.py

Also fixed a few skipped and xfailed tests

Compile regexes

---

cf_xarray/criteria.py
cf_xarray/tests/test_accessor.py

xref https://github.com/NOAA-GFDL/MDTF-diagnostics/issues/198
cc @tsjackson-noaa

Some CMIP6 support

---

cf_xarray/accessor.py
doc/examples/introduction.ipynb

Add cf table reference

---

cf_xarray/units.py

This is a baby PR that adds "PSU" to the list of recognized salinity units.

added PSU to psu units

---

cf_xarray/__init__.py
cf_xarray/accessor.py
cf_xarray/options.py
cf_xarray/tests/test_accessor.py
cf_xarray/tests/test_options.py
cf_xarray/units.py

This makes the support for the custom_criteria more robust.

Copy over xarray's set_options context manager

---

cf_xarray/accessor.py
cf_xarray/scripts/make_doc.py
ci/doc.yml
doc/Makefile
doc/conf.py
doc/contributing.rst
doc/examples/index.rst

Closes #248 and resolves all sphinx warnings

docs cleanup

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

Rework plotting heuristics.

---

setup.cfg

@dcherian is this OK? Should we add a min version?

add xarray as a dependency

---

cf_xarray/accessor.py
cf_xarray/helpers.py
cf_xarray/units.py
doc/examples/introduction.ipynb

I was reading a bit the code and found these.

fix some minor typos

---

ci/doc.yml
doc/_static/style.css
doc/conf.py
doc/examples/introduction.ipynb

Switch to furo theme

---

cf_xarray/accessor.py
doc/whats-new.rst

Fix np scaler warning in `_drop_missing_variables()`

---

doc/bounds.md
doc/dsg.md
doc/index.rst
doc/selecting.md
doc/whats-new.rst

More doc updates

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

CMIP6 likes the "--OPT" value.
Closes #216

Ignore bad cell_measures attributes

---

cf_xarray/tests/__init__.py
cf_xarray/tests/test_accessor.py

See PR #289
The PR was merge few minutes before I committed the test. This new test failed before the PR #289, and passes now (it replaces a test that passes before the PR #289).

fix test for datetime

---

cf_xarray/accessor.py
cf_xarray/options.py
cf_xarray/tests/test_accessor.py

Add option to disable warnings about missing variables

---

cf_xarray/data/cf-standard-name-table.xml

cf-standard-name-table v79

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

Allow adding bounds to general coordinate vars

---

cf_xarray/helpers.py

correct docstring

---

cf_xarray/accessor.py
doc/whats-new.rst

Check attrs before printing guess

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

Print variable name for cell measures warnings

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py
doc/whats-new.rst

allow custom criteria for name of DataArray

---

README.rst

https://github.com/badges/shields/issues/8671

Fixed build badge

---

cf_xarray/accessor.py
cf_xarray/tests/test_accessor.py

Check compatibility of coordinate variable dimensions before assignment.

---

cf_xarray/utils.py
doc/whats-new.rst

Fixes #501
Copies the code that was removed from xarray in the latest version.

Remove pycompat ref in utils

---

cf_xarray/geometry.py

Avoid one deepcopy in geometry encoding
