xarray-contrib/cf-xarray

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py
`.isel(X=5, Y=5)` → `.isel(xi_rho=5, xi_u=5, xi_v=5, eta_rho=10, ...)`
Closes #13
=> Allow expanding single keys to multiple keys.

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py
This adds `_plot_decorator` that is used to set default kwargs when appropriate CF attributes are set.
Right now it only looks for `positive="down"` and sets `xincrease, yincrease` appropriately. 
This only works when `x` and `y` are explicitly specified. To work when` x=None` or `y=None` we'll have to do our own autoguessing. This could be useful the y-axis is `Z` or `Y` (priority order) and xaxis is `T`, `X` (priority order). Will leave that for later.
=> Set default plotting kwargs

.pre-commit-config.yaml, cf_xarray/accessor.py, cf_xarray/tests/datasets.py, cf_xarray/tests/test_accessor.py
=> getitem support for standard_name

cf_xarray/accessor.py, cf_xarray/tests/datasets.py, cf_xarray/tests/test_accessor.py, doc/examples/introduction.ipynb
This makes it so that
``` python
>>> ds.cf.sizes
{'X': 53, 'Y': 25, 'T': 2920, 'longitude': 53, 'latitude': 25, 'time': 2920}
```
An error is raised for Datasets with multiple `X` variables
``` python
AttributeError: cf_xarray can't wrap attribute 'sizes' because there are multiple values for 'X' viz. {'x1', 'x2'}. There is no unique mapping from 'X' to a value in 'sizes'.
```
=> Rewrite dicts like .chunks and .sizes

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py, doc/whats-new.rst
Adds a bounds variable assuming equal spacing on either side of a
coordinate label. The variable is named f"{dim}_bounds" and raises
an error if there is an existing variable with the same name.
Also adds appropriate "bounds" attribute to the coordinate variable.
Fixes #35
=> Add .cf.add_bounds to guess bounds for 1D coord.

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py
Fix apply_mapper to set defaults when receiving an empty list from
mapper functions. This got removed in an earlier cleanup commit by
mistake.
=> Fix bug where unmapped keys were discarded.

cf_xarray/accessor.py
apply_mapper can now take a tuple of mappers.
It will apply them sequentially. Mappers are expected to return []
if no mapping is possible. A list of results e.g. [[], ["lon"]] is then
unpacked to ["lon"] and returned. If none of the mappers apply or if
more than one mapper can apply, an error is raised.
=> Fix application of multiple mappers.

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py, doc/contributing.rst, doc/examples/introduction.ipynb, setup.cfg
1. If passes a scalar key, there must be only one variable that matches
the key
2. To get back all variables, pass a list ds.cf[["longitude"]] for
example.
I think this is more consistent with xarray semantics.
=> Rework getitem

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py, doc/api.rst
Closes #32 
Return bounds variables when returning a Dataset
1. Unfortunately, we cannot return bounds variables with
`ds.cf["latitude"]` for e.g. DataArrays cannot have
coordinate variables with dimensions that are not on
the core variable.
Actually, if we go through the _to_temp_dataset,
assign bounds to coords, then_from_temp_dataset
route, this will work. But pretty sure that's not
intended.
2. ds.cf[["air"]] will return bounds variables for dimensions
if appropriate.
=> Support for bounds.

ci/doc.yml
I just moved `sphinx-autosummary-accessors` from my own organization to `xarray-contrib`. Since right now it's only used by the repositories in `xarray-contrib` I can afford to submit PRs to all of them :grinning:
Not sure when I can release that extension and upload to PyPI / conda-forge (that is currently blocked by issues with `AccessorCallable` in combination with `autosummary` – once fixed the `alias of ...` summary will be replaced by the summary line in the `__call__` docstring), but once I do I'll ping you.
=> update the location of sphinx-autosummary-accessors

ci/doc.yml
I recently released `sphinx-autosummary-accessors`, so installing from PyPI should be preferred over installing from github. I'm also planning to create a conda-forge recipe (see xarray-contrib/sphinx-autosummary-accessors#15), but that will probably still take some time.
Edit: also, I noticed the documentation of your `.cf.plot` accessor is broken. You might fix that by using a descriptor other than `property`, see pydata/xarray#3988.
=> install from pypi

ci/doc.yml
The extension is on `conda-forge`, so you should be able to install that instead of falling back to `pip`.
=> install sphinx-autosummary-accessors from conda-forge

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py
See #84 
@kthyng this will prevent `guess_coord_axis` from trying set attrs for `xi_*` when there is no corresponding array.
=> Minor fixes to avoid guess attrs for unindexed dim

cf_xarray/__init__.py, cf_xarray/accessor.py, cf_xarray/helpers.py, cf_xarray/tests/datasets.py, cf_xarray/tests/test_accessor.py, cf_xarray/tests/test_helpers.py, doc/api.rst, doc/examples/introduction.ipynb, doc/whats-new.rst
This PR adds a  `ds.cf.get_corners(key)` method for the Dataset accessor. This method transforms the bounds given in the conventionnal CF format to a "corners" format:
- For grids with 1D coords: `lon_bnds` of shape `(nlon, 2)` becomes `lon_corners` of shape `(nlon + 1)`.
- For grids with 2D coords: `lon_bnds` of shape `(nx, ny, 4)` becomes `lon_corners` of  shape `(nx + 1, ny + 1)`. 
New dimensions are named `{dim}_corners}`.  I added a dataset to the tests with 2D coords and both bounds and corners, it's called "mollwds" cause the (X,Y) -> (lon, lat) transform is a mollweide projection.
Caveats:
- The 2D case is kinda ugly. It is because I found no elegant way of testing if bounds were given in a clockwise or counterclockwise manner. So what that does is compute the clockwise case, …
=> Compute corners from bounds

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py, doc/whats-new.rst
Closes #109
`.axes`, `.coordinates`, `.cell_measures`, `.standard_names` return dictionaries mapping standard name to variable names.
`.get_standard_names` still returns a list of standard names.
=> properties now return dictionaries rather than lists

cf_xarray/accessor.py
My goal in this is to expand what is matched to "count" as time when `guess_coord_axis` is run to include other time frequencies that might result from for example a groupby call. With the change in this PR, the following is now possible
This avoids needing to add attributes after the calculation 
`ds.temp.isel(xi_rho=300,s_rho=-1).cf.groupby("T.hour").mean(skipna=False)`
=> added time frequencies to regex for T

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py, doc/examples/introduction.ipynb, doc/whats-new.rst
Closes #116 
After some thought I came up with this implementation. 
I kept the hardcoded `_CELL_MEASURES`, so defined CF measures (area and volume) are always displayed by `describe()`.
User defined measures are added to `_CELL_MEASURES` when the `CFAccessor` is initialized.
I had to comment out `_get_measure_variable` in the `_build_docstring` (not sure if it needs to be substituted with something else).
What do you think?
=> new cell measures implementation

cf_xarray/accessor.py
As noted in pangeo-data/xESMF#55 and per CF conventions, it is incorrect to assume a coordinate that has a 'grid_longitude' standard name is indeed a 'longitude' coordinate. For example, this standard name is also used by rotated pole coordinates (usually 'rlon' and 'rlat').
This PR removes the `grid_X` standard names.
=> Remove grid_longitude from longitude standard names

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py, doc/whats-new.rst
I forgot about `drop_dims` in #145.
=> add support for drop_dims

.gitignore, cf_xarray/scripts/make_doc.py, cf_xarray/tests/test_scripts.py, doc/conf.py, doc/contributing.rst, doc/criteria.rst, doc/examples/introduction.ipynb, doc/index.rst, doc/whats-new.rst, setup.cfg
Close #138: I'd also find it very useful so I gave it a go.
I've added a script to create a table with coordinate criteria in the documentation.
Not sure if I placed the table and the script in the right place (maybe the *script should just go in `doc/`?), but that should be easy to change.
Right now it creates this.
=> add coordinate criteria table in docs

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py, doc/api.rst, doc/whats-new.rst
Fixes (partially) pangeo-data/xESMF#72.
Simple method, practically a copy of code suggested by @dcherian, to get the "bounds" dimension name for a given key.
=> Add "get_bounds_dim_name"

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py, doc/api.rst, doc/examples/introduction.ipynb, doc/whats-new.rst
Tiny change.
In this case:
```python
from cf_xarray.tests.datasets import airds
airds.rename_dims(lon="x", lat="y").reset_coords().cf.describe()
```
currently `longitude` and `latitude` are not shown by `.describe()`.
This change shows them in the Standard Names section.
=> show coords std names

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py
Oops sorry, I made a mistake in #150 .
Additional cell measures were not shown in `__repr__`.
Default measures (area and volume) are now shown first, then additional measures are shown in alphabetical order.
The n/a row only applies to area and volume.
=> fix cell measures __repr__

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py
NEMO domain files often don't have attributes, I've added a few regex that should allow to guess most of the axes/coords:
- T, time: `t`, `time_{counter,instant,centered}`
- Z, vertical: `z`, `nav_lev`, `gdep{t,u,v,f,w,uw,vw}_{0,1d}`, `depth{t,u,v,f,w,uw,vw}`
- longitude: `nav_lon`, `glam{t,u,v,f}`
- latitude: `nav_lat`, `gphi{t,u,v,f}`
=> Add NEMO regex

cf_xarray/accessor.py, cf_xarray/datasets.py, cf_xarray/tests/test_accessor.py, doc/examples/introduction.ipynb, doc/whats-new.rst
@dcherian were you thinking something along these lines?
Currently `_get_dims/coords/indexes` use `_get_axis_coord` and `_get_with_standard_name`.
We can probably get rid of `_get_axis_coord` and `_get_with_standard_name`, I just wanted to check first whether that's the way to go as they are used in many places. Not sure if all `_get_axis_coord` can be replaced by the same function (e.g., `_get_coords`) or it's not that simple.
All tests are passing, I didn't add new tests yet.
=> Rework mappers to be more general

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py
Small fix for #179.
Modified `_get_with_standard_name` so that when used on a `DataArray`, it cannot return itself (the `<this-array>` variable in the temp dataset). This match the previous behavior (I think?) and fits the returned error message : `ds.air.cf['air_temperature']` fails because 'air_temperature' doesn't appear in `ds.air.cf`.  But `ds.lat.cf['latitude']` works, since 'latitude' appears in `ds.lat.cf`.
Also added a minimal test.
=> Do not return <this-array> instances

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py, doc/examples/introduction.ipynb
=> rename_like warns about conflicting variables

cf_xarray/accessor.py, cf_xarray/criteria.py, cf_xarray/scripts/make_doc.py
=> Refactor out coordinate criteria to criteria.py

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py, doc/examples/introduction.ipynb
Closes #184 
I introduced `skip` rather than `do`. What do you think?
=> add skip to rename_like

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py, doc/api.rst, doc/whats-new.rst
Closes #210
Closes #215 
What should we do with DataArrays, where we can't have bounds because of the extra dimension?
Currently nothing specific is done. For example, when we extract a `DataArray` from a `Dataset`, `da.cf.bounds` is not empty, as we don't pop the `bounds` attribute from the coordinates. However, `da.cf.__repr__` shows `Bounds:  n/a` as the bounds variables are not present.
Should `cf.bounds` only include variables present in the object (and warn about missing bounds)?
Should `cf.bounds` be a property of `Datasets` only?
Should we pop the `bounds` attribute from coordinates when extracting a `DataArray`?
Should we only show `Bounds` in the representation of Datasets?
=> add bounds property

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py, doc/api.rst, doc/whats-new.rst
Closes #211
cc @tsjackson-noaa
=> Add .cf.formula_terms

.github/workflows/ci.yaml, cf_xarray/tests/test_units.py, cf_xarray/units.py, ci/environment-no-optional-deps.yml, ci/environment.yml, ci/upstream-dev-env.yml, doc/whats-new.rst, setup.cfg
Closes https://github.com/xarray-contrib/pint-xarray/issues/26
As discussed in https://github.com/xarray-contrib/pint-xarray/issues/26, this PR adds a copy of MetPy's Pint registry (which has some customization to better support CF/UDUNITS-style units most commonly found in CF-compliant NetCDF files) to cf-xarray. However, right now that is *all* that this does at this point, and so, I'd like to put this up now as a work-in-progress and hopefully start a more detailed conversation about how to move forward with this:
- **Main Question**: how should cf-xarray relate to pint-xarray?
- inherit `.pint` accessor in the `.cf` accessor and use with this registry?
- set this ported registry to the application registry and provide documentation on how to use it with `pint-xarray`? <-- my …
=> Add unit support to cf-xarray

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py, cf_xarray/utils.py, doc/examples/introduction.ipynb
=> Don't apply mappers to DataArrays

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py, doc/whats-new.rst
`rename_like` also updates the `bounds` and `cell_measures` attributes.
=> Improve `rename_like`

.tributors, .zenodo.json, CITATION.cff
Following Earthcube review comments.
I used
https://citation-file-format.github.io/
https://con.github.io/tributors/docs/getting-started
https://github.com/castelao/inception
for guidance. In theory we could set up  a tributors github action but i'll leave that for later.
=> Add CITATION.cff, tributors, zenodo.json

cf_xarray/accessor.py, cf_xarray/criteria.py, cf_xarray/scripts/make_doc.py
These changes are in support of updating the `_get_axis_coord` logic to be a bit more generalized so the same logic can be used to find axis coordinates and to pull out variables (that is a future step).
The coordinate_criteria dictionary in criteria.py is now inverted so the keys are axes and coord names with values of valid attribute types and values.
The function `_get_axis_coord()` was updated to try to account for this change in the `coordinate_criteria` dictionary though it may not be correct quite yet. The tests did not all pass.
=> Change coord criteria to {cf_name: criteria}

cf_xarray/accessor.py, cf_xarray/criteria.py, doc/whats-new.rst
=> Support indexing by cf_role for DSG datasets

cf_xarray/helpers.py, doc/whats-new.rst
xref #163 which is the inverse of this
=> Convert nD bounds arrays to (n-1)D vertex arrays

cf_xarray/accessor.py, cf_xarray/datasets.py, cf_xarray/tests/test_accessor.py, ci/doc.yml, doc/api.rst, doc/whats-new.rst
xref #199
Implements rich comparisons and .isin. I changed my mind and dropped the `.flag`.
@jbusecke I copied your code over but had to make some changes to match the conventions. Try it out and let me know how it works!
``` python
import cf_xarray
import numpy as np
import xarray as xr
da = xr.DataArray(
[1, 2, 1, 1, 2, 2, 3, 3, 3, 3],
dims=("time",),
attrs={
"flag_values": [1, 2, 3],
"flag_meanings": "atlantic_ocean pacific_ocean indian_ocean",
"standard_name": "region",
},
name="region",
)
da.cf
```
```
CF Flag variable with mapping:
{'atlantic_ocean': 1, 'pacific_ocean': 2, 'indian_ocean': 3}
Coordinates:
- CF Axes:   X, Y, Z, T: n/a
- CF Coordinates:   longitude, latitude, vertical, time: n/a
- Cell Measures:   area, volume: n/a
- Standard Names:   n/a
- Bounds:   n/a
```
```python …
```
=> Add support for flag variables.

cf_xarray/helpers.py, cf_xarray/tests/test_helpers.py
The recent changes to `bounds_to_vertices` (#250) broke the case where `order=None` and `"counterclockwise"` is the good solution. (The tests were testing the case where `order=None` and solution is `"clockwise"`) We realized it in xESMF : pangeo-data/xESMF#112.
I missed that during my review, but the problem is simply a change in the axes order within the function... This adds a test and fixes the bug.
=> Fix bounds_to_vertices

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py
Closes #254 
I haven't tried with other attributes, but it looks like introducing a decorator that only returns existing keys would work well.
Thoughts? If you think that this is the way to go, I'll try to implement it for `cell_measures`, `formula_terms`, ...
cc: @dcherian @tomvothecoder @huard
=> Drop missing variables

.gitignore, MANIFEST.in, cf_xarray/utils.py, doc/examples/introduction.ipynb, setup.cfg, setup.py
@dcherian this is not ready yet but I want to place it here so I don't forget.
Relying on `pkg_resources` can make the initial import of cf_xarray quite slow depending on the packages you have installed. This PR changes the logic a bit to avoid relying on that but rather make use of  setuptools-scm file `_version.py`.
=> Remove pkg resources

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py
Fixes #229.
I modified `apply_mapper` to fit with xarray's criterion for a `DataArray` name, meaning that `key` must be hashable (and not only simply a string). I added a test for the `_to_temp_dataset()` case. All other tests pass.
As far as I understand, the `key` is tested either against string parsed from the attributes or against variable names in the dataset. In the first case, passing a non-string doesn't raise anything but it's also useless. In the second case, that's precisely the point : "being hashable" is the same constraint as in xarray.
But maybe others have a better idea of the edge cases? I can add more tests, I just don't know what to test!
=> Allow hashable keys (not only strings) 

setup.cfg, setup.py
@dcherian the URL in the setup.cfg is for the GH repo but the one in the setup.py is for the docs. Which one do you want to keep?
=> single source for metadata

.binder/environment.yml
@dcherian we don't need qt so mpl base should suffice. That reduces the size of the image and make binder load a bit faster.
I also remove the minor pin on Python to let the solver get whatever latest one works with the dependencies. Should be OK for demos.
=> Reduce binder size and hopefully make it faster

.pre-commit-config.yaml
Apparently, the tool has been abandoned by the maintainer: the repository has been archived. Since it is failing I believe it is time to remove it (I don't really understand its purpose so I might be wrong, though)
=> remove the isort seeding hook

doc/units.md
follow-up to #278. Since `pint` doesn't pass the modifier to the formatter at the moment, `":cf"` and `":~cf"` do the same thing right now. Despite that, it's better to add the `~` modifier when talking about the short format. 
Edit: see hgrecco/pint#1448
=> explicitly use the short formatter in the docs

cf_xarray/units.py
I needed the "degC = celsius"  aliases so I copied that and more from xclim.
cc @jthielen
xref #225
=> More unit definitions from xclim

cf_xarray/tests/test_accessor.py, cf_xarray/utils.py
Fixes #285 
I added 2 tests to verify this PR, they were not passed before and are now passed.
After a small benchmark, it seems that my proposed solution in #285 is not the fastest. I changed it to another similar solution.
=> fix cf_xarray.utils._is_datetime_like

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py
I think this is the problem
1.  __init__ isn't called during unpickling.
2. So self._obj is undefinited and goes through our _getattr machinery
which requires self._obj as an argument, so we get a RecursionError
For some reason this is only (so far) triggered when stuffing xarray objects
in dask.delayed tasks and a distributed scheduler.
The test of pickling `da.cf` fails on main, so it would be good to fix
that in general.
=> Fix unpickling by defining __setstate__

cf_xarray/accessor.py, cf_xarray/datasets.py, cf_xarray/tests/test_accessor.py, doc/parametricz.md, doc/whats-new.rst
The vertical decoding has been added for `ocean_sigma_coordinate` and the free surface variable has been expanded dimensionally for all the calculations so that the results preserve the standard ordering of time, vertical, lat/Y, lon/X. Three of the tests do not work anymore, though. Expanding dimensionally apparently bumps the attributes off of s_rho, for one. For another, the values are very similar but do not match anymore — not sure why. Interested to see what @dcherian thinks!
=> new vertical coord decode and reordering

cf_xarray/__init__.py, cf_xarray/coding.py, cf_xarray/tests/test_coding.py, doc/api.rst, doc/coding.md, doc/conf.py, doc/index.rst, doc/whats-new.rst
Uses "compression by gathering".
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#compression-by-gathering
https://github.com/pydata/xarray/issues/1077#issuecomment-644442679
This is useful and opt-in so let's provide it.
=> Add encoder, decoder for MultiIndexes.

cf_xarray/accessor.py, cf_xarray/datasets.py, cf_xarray/tests/test_accessor.py, doc/api.rst, doc/dsg.md, doc/whats-new.rst
1. Add cf_roles attribute
2. Add to .cf.keys()
3. Add to repr
Closes #305
=> Increased support for cf_role

.github/dependabot.yml, .github/workflows/ci.yaml
I noticed we are a little behind with some of the actions.
Dependabot should update everything periodically.
I also added a quite new GH feature to [cancel in-progress jobs](https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-concurrency-to-cancel-any-in-progress-job-or-run).
=> Dependabot

.gitignore, cf_xarray/tests/test_units.py, cf_xarray/units.py
This PR adds "Celsius" as a valid alias for the standard "celsius".
This happens in some instance of E-OBS datasets: https://climexp.knmi.nl/showmetadata.cgi?field=ensembles_025_tg_mo&id=someone@somewhere
It is a backport from xclim units update: https://github.com/Ouranosinc/xclim/pull/1068 as suggest by the maintainer in the dedicated issue.
=> ENH: Add "Celsius" alias

.github/workflows/ci.yaml, .github/workflows/parse_logs.py, .github/workflows/upstream-dev-ci.yaml
=> CI improvements

cf_xarray/datasets.py
This hides all variables in `cf_xarray.datasets` that are not `xr.Dataset` such that `cf_xarray.datasets.<Tab>` is more helpful.
=> cf_xarray.datasets: hide auxiliary variables

cf_xarray/accessor.py, cf_xarray/datasets.py, cf_xarray/tests/test_accessor.py
This converts several (unnecessary?) deep xarray copies to shallow copies throughout tests + `accessor.py`. I was surprised by the quite slow performance of this otherwise lightweight-seeming package and traced the issue to the copy calls.
As far as I can tell, this package only changes attribute dictionaries and adds new data/coordinate variables (i.e., does not touch the numpy arrays underlying each DataArray). If that's correct, `deep=True` should never be required, since both shallow and deep copies copy the various dictionaries associated with each xarray object (i.e. `data_vars`, `coords`, `attrs`, `encoding`). The deep version only differs in that it copies the (possibly enormous) underlying numpy arrays.
Here's a quick demo of "shallow" xarray copies (xarray version `2022.3.0`): …
=> Performance improvement: Convert unnecessary (?) deep copies to shallow copies

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py
With https://github.com/pydata/xarray/pull/5514 it has become practice (at least for me) to occasionally disable the coordinates attribute to be written to file by setting `ds['var'].encoding['coordinates'] = None`. If used too generously, this may however lead to an AttributeError in the cf-xarray accessor:
>        if "coordinates" in obj.encoding:
>           search_in.update(obj.encoding["coordinates"].split(" "))
>E           AttributeError: 'NoneType' object has no attribute 'split'
I suggest this small update to keep that from happening.
=> Accounting for NoneType coordinates in attrs/encoding

cf_xarray/tests/test_accessor.py
Fixes #365
I believe that pydata/xarray#7089 fixed an issue with deepcopying that we were "using" to check if attributes were changed after the accessor is called. Now  when we use `ds.copy(deep=True)` , well the copy is indeed deep and we can't compare the attribute's `id`. 
This PR changes the `id`check to a complete equality check.
=> Replace id comparison by value comparison in tests

cf_xarray/geometry.py, doc/whats-new.rst
This is a small fix to support  `shapely` 2.0. Changes were made between 1.8 and 2 that removed the implicit array interface the previous  `points_to_cf` was using.  We now need a check for  "MultiPoints", but the change still is minimal.
This works with the previous shapely too.
=> Fix for shapely 2.0

doc/index.rst
After a change in COSIMA-recipes docs `tutorials` -> `Tutorials`
cc @aidanheerdegen, @Angus-g
=> Update link to COSIMA tutorial

cf_xarray/criteria.py, cf_xarray/tests/test_accessor.py
closes #425 
This PR updates criteria and regex for identifying `X` and `Y` axis in rotated pole grids.
=> identify `X` and `Y` in rotated pole grids

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py
cf-xarray is not finding T as a time axis due to a KeyError. This first checks to see if the key is in sgrid_axes before using that.
Closes https://github.com/xarray-contrib/cf-xarray/issues/434
=> Don't look for `T` in sgrid axes

.github/workflows/pypi.yaml
There's a relatively new feature called [trusted publishing](https://docs.pypi.org/trusted-publishers/) on PyPI (based on OpenID Connect) that aims to replace the long-lived API tokens. Github and the action we use to upload to PyPI also [support it](https://github.com/pypa/gh-action-pypi-publish#trusted-publishing).
One main advantage is that this also allows creating *new* PyPI projects, so we don't have to manually upload we a user's API token to create the project, create a restricted API token for the project and use that.
I'm submitting a PR here first before doing the same for `xarray` just to make sure this works just as smoothly for larger projects as for the [little project](https://github.com/umr-lops/xarray-safe-rcm) I just used to try this out.
@dcherian, if this sounds good …
=> use trusted publishing

cf_xarray/formatting.py
=> Better flag masks repr

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py
closes #448 
This implements the fix suggested by @dcherian in #448
=> added `ValueError` for missing `grid_mapping` variable

cf_xarray/tests/__init__.py
It is imported but unused (tests passes without it). Removing this import will make `cf_xarray` ready to Python 3.12.
---
Edit: Changing to packaging.version.parse is not the same thing as `LooseVersion`, see https://discuss.python.org/t/add-looseversion-to-pypa/24359/6,  but we should be OK b/c here b/c the packages checked all follow PEP440.
=> remove distutils

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py
Handle the case where `lat` and `lat_bounds` have same attributes.
Closes #442
=> Fix get_bounds_dim_name regression.

.github/workflows/ci.yaml, .github/workflows/upstream-dev-ci.yaml
=> Switch to setup-micromamba

.github/workflows/pypi.yaml
The upload action failed recently because the `python-version` was interpreted as a float value. This ensures that it is seen as a string.
The action would need to be re-triggered with these new changes to be used to upload the package to PyPI
=> Set python-version as string

pyproject.toml
Before:
```
---------- coverage: platform linux, python 3.10.13-final-0 ----------
Name                               Stmts   Miss  Cover
------------------------------------------------------
cf_xarray/__init__.py                  8      0   100%
cf_xarray/_version.py                  1      0   100%
cf_xarray/accessor.py               1053     62    94%
cf_xarray/coding.py                   53      7    87%
cf_xarray/criteria.py                 17      2    88%
cf_xarray/datasets.py                 89      0   100%
cf_xarray/formatting.py              144     12    92%
cf_xarray/geometry.py                 98      2    98%
cf_xarray/helpers.py                  64      6    91%
cf_xarray/options.py                  23      0   100%
cf_xarray/scripts/make_doc.py         28      1    96% …
```
=> Do not include tests when calculating coverage

cf_xarray/accessor.py, cf_xarray/coding.py, cf_xarray/geometry.py, cf_xarray/helpers.py, cf_xarray/options.py, doc/conf.py, doc/examples/introduction.ipynb
Docs build is broken on main. This seems to fix it locally. Ref: https://github.com/sphinx-doc/sphinx/issues/11094#issuecomment-1372994091
=> Fix docs build

cf_xarray/accessor.py, cf_xarray/criteria.py, cf_xarray/formatting.py, cf_xarray/options.py, cf_xarray/tests/test_accessor.py, cf_xarray/tests/test_helpers.py, cf_xarray/units.py, cf_xarray/utils.py, pyproject.toml
=> repo-review round 2

cf_xarray/geometry.py, cf_xarray/tests/test_geometry.py, pyproject.toml
I started on this at the SciPy sprints with the idea of pushing forward the work described in this ticket: https://github.com/xarray-contrib/xvec/issues/48. It took me a while to get the logic right :sweat_smile: so I wanted to make sure it was somewhere public in case I don't get a chance to come back to it in the near future.
=> Add conversion between cf and shapely for lines

cf_xarray/datasets.py, cf_xarray/formatting.py, cf_xarray/tests/test_accessor.py
I would like to add larger bit depth support for displaying the flags / flag_masks as in #491 . Thank you for considering this.
=> Add larger bit depth for displaying flag_masks

cf_xarray/geometry.py
=> Highlight support for line geometries in docstring

cf_xarray/tests/test_units.py, cf_xarray/units.py
The idea is to accept integer units of `1` for dimensionless, which is explicitly allowed by the CF conventions (we could, however, pass through objects that are not integers unmodified).
Note that `pint` itself doesn't really like the idea of integer units, so this will only work with `ureg.parse_units(1)`: `ureg.Quantity(1, 1)` will raise before any preprocessor is called.
=> cast units to `str` before applying any other preprocessor

pyproject.toml
modern ruff versions complain about this
=> ruff settings: move 'ignore' to 'lint' section

cf_xarray/helpers.py
numpy 2 removed `np.NaN` in favor of `np.nan`
=> numpy 2 compat

cf_xarray/geometry.py, ci/doc.yml, doc/geometry.md
I finally got around to taking a crack at #497. Feel free to add anything.
=> Add docs about converting between shapely and cf

cf_xarray/__init__.py, cf_xarray/accessor.py, cf_xarray/criteria.py, cf_xarray/datasets.py, cf_xarray/formatting.py, cf_xarray/geometry.py, cf_xarray/tests/conftest.py, cf_xarray/tests/test_accessor.py, cf_xarray/tests/test_geometry.py, doc/api.rst, doc/coding.md, doc/geometry.md
These differ from `shapely_to_cf` and `cf_to_shapely` by returning all variables. Those function, simply encode and decode geometry-related variables.
cc @jsignell 
xref https://github.com/xarray-contrib/xvec/issues/26
=> Add geometry encoding and decoding functions.

cf_xarray/tests/test_units.py, cf_xarray/units.py, doc/units.md, pyproject.toml
Fixes #522 and hgrecco/pint#2024.
- Rewrite of the custom unit formatter to properly use the tools of pint instead of relying on regex.
- To preserve backwards compatibility the `pint.formatter` call  changes according to the installed version of  `pint`.
- Before, `f"{u:cf}"` and `f"{u:~cf}"` returned the same thing except for "dimensionless". This shortening is done explicitly in the new formatter with a `if-else` in case it was already done by `pint`.
- Removed a few unneeded lines 
+  "percent" was always printed as "%" for all supported pint versions, so I don't know why it as there.
+ The formatter's declaration never raised ImportError, so I think the `try-except` was a legacy from something else. 
- Added some warnings to the documentation about non-udunits units.
- Added …
=> Rewrite unit formatter for pint 0.24 and earlier

cf_xarray/geometry.py, cf_xarray/tests/test_geometry.py, doc/api.rst, doc/geometry.md
This needs
- updated docstrings
- adding GeometryNames to api.rst
- loot more tests
- typing fixes
but it works with all xvec examples!
=> Allow encoding/decoding multiple geometries

cf_xarray/geometry.py, cf_xarray/tests/test_geometry.py
Closes #534
Now we rely on shapely/geos to raise the error, avoiding one pass through all geometries
=> Speed up geometry encoding

cf_xarray/accessor.py, cf_xarray/coding.py, cf_xarray/formatting.py, cf_xarray/scripts/make_doc.py, cf_xarray/sgrid.py, cf_xarray/tests/test_accessor.py, cf_xarray/utils.py, pyproject.toml
@dcherian feel free to close this b/c it may not fit your ideas. I thought it was odd that a min pin is necessary to build cf_xarray but not to run. That can lead to slower solves and, if there is a `xarray>=2022.03.0` feature necessary at run time, one can create a broken environment the way it is. 
I also bumped the linters to use the min support Python version. However, I'm pretty sure ruff reads `requires-python` if you omit those, reducing the amount of things to remember to edit at every version bump.
=> add min xarray pin on run and numpy py ver linters

CITATION.cff, cf_xarray/accessor.py, cf_xarray/parametric.py, cf_xarray/tests/test_accessor.py, cf_xarray/tests/test_parametric.py, doc/parametricz.md
Adds support for parametric vertical coordinates from [CFConventions](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#parametric-v-coord).
=> Adds support for parametric vertical coordinate

cf_xarray/__init__.py, cf_xarray/groupers.py, cf_xarray/tests/test_groupers.py, ci/doc.yml, doc/api.rst, doc/flags.md
=> Add FlagGrouper

.github/workflows/ci.yaml, .github/workflows/upstream-dev-ci.yaml, cf_xarray/__init__.py, cf_xarray/tests/test_groupers.py, ci/environment-all-min-deps.yml, pyproject.toml
=> Fix Grouper import

cf_xarray/accessor.py, cf_xarray/tests/test_accessor.py
Fixes decoding parametric coordinate when calling the accessor method.
=> Fixes decoding parametric coord

cf_xarray/accessor.py
=> Fix imports again

cf_xarray/groupers.py
This avoids hitting this check: https://github.com/pydata/xarray/blob/aa9e2bd407a47cef1ec7f1d9498e4a1118bc440e/xarray/core/groupby.py#L329-L337 and generally seems like a better design
=> FlagGrouper: Encapsulate instead of subclassing UniqueGrouper
